website/urls.py
from django.urls import path
from website import views

app_name = 'website'

urlpatterns = [
    # Login
    path('',views.LoginPageView.as_view(),name='login'),
    # Logout
    path('Logout',views.Logout.as_view(),name='logout'),

    # Student
    path('Student-Registration',views.StudentRegistrationPageView.as_view(),name='StudentRegistration'),
    path('Student-Dashboard',views.StudentDashboard.as_view(),name='student-dashboard'),
    path('Student-Profile-Edit',views.StudentProfileEditView.as_view(),name='student-profile'),

    # Admin
    path('Admin-Registration',views.AdminRegistrationPageView.as_view(),name='AdminRegistration'),
    path('Admin-Dashboard',views.AdminDashboard.as_view(),name='AdminList'),

]

zinfog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date

# Create your models here.

class CustomUser(AbstractUser):
    username = models.CharField(max_length=30, unique=True)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=15)
    birth_date = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to='profile_images/', null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    marks = models.FloatField(null=True, blank=True)
    password_text = models.TextField(null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.birth_date:
            today = date.today()
            self.age = today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
        super().save(*args, **kwargs)
    

website/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse,JsonResponse
from django.contrib.auth import login,logout, authenticate
from django.shortcuts import redirect
from django.contrib.auth.hashers import check_password
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import loader
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.utils.decorators import method_decorator
from datetime import datetime

from website.helper import renderhelper,is_ajax
from website.models import CustomUser
from website.decorators import admin_required,student_required

# Login View
class LoginPageView(View):
    context = {}

    def get(self, request):
        return renderhelper(request,'layout', 'login', self.context)

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        # try:
        #     validate_password(password)
        # except ValidationError as e:
        #     messages.error(request, ', '.join(e.messages))
        #     return renderhelper(request, 'layout','login', self.context)

        # username = CustomUser.objects.get(email=email.lower()).username
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(request, user)
            if user.is_admin:
                return redirect('website:AdminList')
            else:
                return redirect('website:student-dashboard')
        else:
            messages.error(request, 'Username or Password is Incorrect')
            return renderhelper(request,'layout', 'login', self.context)

# Logout View  
class Logout(LoginRequiredMixin,View):
    context={}
    def get(self, request):
        request.session.flush()
        logout(request)
        return redirect('website:login')

# Student Registration   
class StudentRegistrationPageView(View):
    context = {}

    def get(self, request):
        if request.user.is_authenticated:
            messages.info(request, 'Sign out the current user and register a new user')
            return redirect('website:login')
        else:
            return renderhelper(request,'student', 'student_registration', self.context)

    def post(self, request):
        data = CustomUser()
            
        image = request.FILES.get('image')
        name = request.POST['name']
        email = request.POST['email']
        dob = request.POST['dob']
        phone = request.POST['phone']
        password = request.POST['password']
        username = request.POST['username']

        try:
            validate_password(password)
        except ValidationError as e:
            messages.error(request, ', '.join(e.messages))
            return renderhelper(request,'student', 'student_registration', self.context)
        
        try:
            data.name=name
            data.image=image
            if dob:
                dob_date = datetime.strptime(dob, '%Y-%m-%d').date()
                data.birth_date = dob_date
            data.phone=phone
            data.email=email
            data.username=username
            data.set_password(password)
            data.password_text=password
            data.is_student=True   
            data.save()
            login(request,data)
            messages.info(request, 'Account Created Successfully')
            return redirect('website:student-dashboard')
        except:
            messages.info(request, 'Something Went Wrong')
            return renderhelper(request,'student', 'student_registration', self.context)

# Student Dashboard
@method_decorator(student_required, name='dispatch')
class StudentDashboard(View):
    def get(self, request):
        context={}
        path="dashboard"
        user=request.user
        context['data']=user
        context['path']=path
        return renderhelper(request,'student','student_dashboard',context)
    

# Student Profile Edit  
@method_decorator(student_required, name='dispatch')
class StudentProfileEditView(View):
    def get(self, request):
        context={}
        data=request.user
        context['data']=data
        return renderhelper(request,'student', 'student_registration', context)

    def post(self, request):

        data = CustomUser.objects.get(id=request.user.id)

            
        image = request.FILES.get('image')
        print("image",image)
        name = request.POST['name']
        email = request.POST['email']
        dob = request.POST['dob']
        phone = request.POST['phone']
        password = request.POST['password']
        username = request.POST['username']

        try:
            validate_password(password)
        except ValidationError as e:
            messages.error(request, ', '.join(e.messages))
            return renderhelper(request,'student', 'student_registration', self.context)
        
        try:
            data.name=name
            if image:
                data.image=image
            if dob:
                dob_date = datetime.strptime(dob, '%Y-%m-%d').date()
                data.birth_date = dob_date
            data.phone=phone
            data.email=email
            data.username=username
            data.set_password(password)
            data.password_text=password
            data.is_student=True   
            data.save()
            login(request,data)
            messages.info(request, 'Successfully Updated')

        except:
            messages.info(request, 'Something Went Wrong')
        return redirect('website:student-dashboard')


# Admin Registration   
class AdminRegistrationPageView(View):
    context = {}

    def get(self, request):
        if request.user.is_authenticated:
            messages.info(request, 'Sign out the current user and register a new user')
            return redirect('website:login')
        else:
            return renderhelper(request,'admin', 'admin_registration', self.context)

    def post(self, request):
        data = CustomUser()
            
        image = request.FILES.get('image')
        name = request.POST['name']
        email = request.POST['email']
        dob = request.POST['dob']
        phone = request.POST['phone']
        password = request.POST['password']
        username = request.POST['username']

        try:
            validate_password(password)
        except ValidationError as e:
            messages.error(request, ', '.join(e.messages))
            return renderhelper(request,'admin', 'admin_registration', self.context)
        
        try:
            data.name=name
            if image:
                data.image=image
            if dob:
                dob_date = datetime.strptime(dob, '%Y-%m-%d').date()
                data.birth_date = dob_date
            data.phone=phone
            data.email=email
            data.username=username
            data.set_password(password)
            data.password_text=password
            data.is_admin=True   
            data.save()
            login(request,data)
            messages.info(request, 'Admin Created Successfully')
            return redirect('website:AdminList')
        except:
            messages.info(request, 'Something Went Wrong')
            return renderhelper(request,'admin', 'admin_registration', self.context)

# Admin Dashboard   
@method_decorator(admin_required, name='dispatch')    
class AdminDashboard(LoginRequiredMixin,View):
    def get(self, request):
        context = {}
        path="dashboard"
        conditions = Q()
        if is_ajax(request):
            page = request.GET.get('page', 1)
            context['page'] = page
            searchkey = request.GET.get('searchkey')
            status = request.GET.get('status')
            mark = request.GET.get('mark')

            type = request.GET.get('type')
            if type == '1':
                id = request.GET.get('id')
                vl = request.GET.get('vl')
                cat = CustomUser.objects.get(id=id)
                if vl == '2':
                    cat.is_active = False
                else:
                    cat.is_active = True
                cat.save()
                messages.info(request, 'Successfully Updated')

            if searchkey:
                conditions |= Q(name__icontains=searchkey)
            if status:
                conditions &= Q(is_active=status)
            if mark:
                id = request.GET.get('id')
                print(id)
                print("mark",mark)
                CustomUser.objects.filter(id=id).update(marks=mark)
                messages.info(request, 'Mark Updated Successfully')

            data_list = CustomUser.objects.filter(conditions,is_student=True).order_by('-id')
            paginator = Paginator(data_list, 15)

            try:
                datas = paginator.page(page)
            except PageNotAnInteger:
                datas = paginator.page(1)
            except EmptyPage:
                datas = paginator.page(paginator.num_pages)
            context['datas'] = datas
            template = loader.get_template('website/admin/admin_table.html')
            html_content = template.render(context, request)

            return JsonResponse({'status': True, 'template': html_content})


        data = CustomUser.objects.filter(is_student=True).order_by('-id')

        p = Paginator(data, 15)
        page_num = request.GET.get('page', 1)
        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        context["path"]=path
        context['datas'] = page
        context['page'] = page_num
        return renderhelper(request, 'admin', 'admin_view',context)

templates/website/layout/footer.html
{% load static %}

<script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.4.5/swiper-bundle.min.js"></script>


{% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.js"></script> {% endcomment %}

<!-- scripts -->

<script src="{% static 'assets/js/jquery.inview.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/slick.min.js' %}"></script>
<script src="{% static 'assets/js/magnific-popup.min.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>

<script src="{% static 'custom/custom.js' %}"></script>
<script src="{% static 'custom/validations.js' %}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script type="text/javascript" src="https://jeremyfagis.github.io/dropify/dist/js/dropify.min.js"></script>

<script type="text/javascript">
    /*code: 48-57 Numbers*/
    function restrictAlphabets(e){
        var x = e.which || e.keycode;
        if((x>=48 && x<=57))
            return true;
        else
            return false;
    }
  </script>
  <script>
    $("#message_div").fadeOut(1000);
</script>
<script>
    $(document).ready(function () {
      $('.dropify').dropify();
    });
  </script>
</body>

</html>

templates/website/layout/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>



	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>ZINFOG CODELABS</title>
	<link rel="icon" type="image/x-icon" href="assets/images/logos/favicon.svg">

	<!-- fontawosome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

	<!-- animate-css -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

	<!-- fontfamily -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Anek+Bangla:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css" rel="stylesheet">

	<!-- css -->
	<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/slick.min.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/magnific-popup.min.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'assets/css/responsive.css' %}" rel="stylesheet">


	<link href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="https://jeremyfagis.github.io/dropify/dist/css/dropify.min.css">


</head>

<body>




	<header>
		<div class="bg-success p-3 border">

			<div class="container">
		
				<div class="d-flex align-items-center justify-content-end">
					{% if user.is_authenticated %}
					<span class="navbar-brand me-auto" style="color: yellow;"><b>Hello, {{ user.name }}</b></span>
				   {% else %}
				   <h5 class="navbar-brand me-auto" style="color: yellow;">You are not logged in</h5>
				   {% endif %}
					{% if user.is_authenticated %}
					<h5 class="ms-3"><a href="{% url 'website:login' %}" class="text-white text-decoration-none">Home</a></h5>
					<h5 class="ms-3"><a {% if user.is_admin %} href="{% url 'website:AdminList' %}" {% else %} href="{% url 'website:student-dashboard' %}" {% endif %}class="text-white text-decoration-none">{% if user.is_admin %} Admin Dashboard {% else %} Student Dashboard {% endif %}</a></h5>
					<h5 class="ms-3"><a href="{% url 'website:logout' %}"class="text-white text-decoration-none">Logout</a></h5>
					{% else %}
					<h5 class="ms-3"><a href="{% url 'website:login' %}"class="text-white text-decoration-none">Login</a></h5>
					{% endif %}
				</div>
			</div>
		</div>
	</header>

templates/website/layout/login.html
{% include "website/layout/header.html" %}

<section class="pt-5">
	<div class="container">
		<h1 class="text-center" style="color: green; font-size:3em;"><b>ZINFOG CODELABS</b></h1>
		<hr>
		
		{% if messages %}
        <div id="message_div" class="succs-msg">
        {% for message in messages %}
                <label class="form-group" style="">
                    <p style="color:red;">{{message}}</p>
                </label>
            {% endfor %%}
        </div>
        {% endif %}
		{% if user.is_authenticated %}

		<h3 style="color: blue; font-size:3em;"><b>{{request.user.name}}</b></h3>
		<h4 style="color: blue; font-size:3em;"><b>{{request.user.email}}</b></h4>
		<h4 style="color: blue; font-size:3em;"><b>{{request.user.phone}}</b></h4>
		{% else %}
		<div class="text-center mt-5">
			<h3>Login</h3>
		</div>
		<form class="login100-form validate-form" method="post" id='login_form'>
			{% csrf_token %}
	
		<div class="m-auto text-center w-50">
			<input type="text" placeholder="Username" class="w-50 mt-4 p-2" required name="username" value="{{username}}" maxlength="15" minlength="5">
			<input type="password" placeholder="Password" class="w-50 p-2 mt-4" required id="password" name="password" value="{{password}}">
			<div class="login-btn text-center mt-4">
			<button type="submit" class="login100-form-btn btn-primary p-2" id="login_btn"> Login </button>
			<p class="pt-5">Create a new account? <span><a href="{% url 'website:StudentRegistration' %}">Student</a></span> /  <span><a href="{% url 'website:AdminRegistration' %}">Admin</a></span> </p>
			</div>
		</div>
		</form>
		{% endif %}
		
	</div>
</section>

{% include "website/layout/footer.html" %}