website/urls.py
from django.urls import path
from website import views

app_name = 'website'

urlpatterns = [
    # Login
    path('',views.LoginPageView.as_view(),name='login'),
    # Logout
    path('Logout',views.Logout.as_view(),name='logout'),

    # Student
    path('Student-Registration',views.StudentRegistrationPageView.as_view(),name='StudentRegistration'),
    path('Student-Dashboard',views.StudentDashboard.as_view(),name='student-dashboard'),
    path('Student-Profile-Edit',views.StudentProfileEditView.as_view(),name='student-profile'),

    # Admin
    path('Admin-Registration',views.AdminRegistrationPageView.as_view(),name='AdminRegistration'),
    path('Admin-Dashboard',views.AdminDashboard.as_view(),name='AdminList'),

]

zinfog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('website.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date

# Create your models here.

class CustomUser(AbstractUser):
    username = models.CharField(max_length=30, unique=True)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=15)
    birth_date = models.DateField(null=True, blank=True)
    image = models.ImageField(upload_to='profile_images/', null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    marks = models.FloatField(null=True, blank=True)
    password_text = models.TextField(null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.birth_date:
            today = date.today()
            self.age = today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
        super().save(*args, **kwargs)
    

website/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse,JsonResponse
from django.contrib.auth import login,logout, authenticate
from django.shortcuts import redirect
from django.contrib.auth.hashers import check_password
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import loader
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.utils.decorators import method_decorator
from datetime import datetime

from website.helper import renderhelper,is_ajax
from website.models import CustomUser
from website.decorators import admin_required,student_required

# Login View
class LoginPageView(View):
    context = {}

    def get(self, request):
        return renderhelper(request,'layout', 'login', self.context)

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        # try:
        #     validate_password(password)
        # except ValidationError as e:
        #     messages.error(request, ', '.join(e.messages))
        #     return renderhelper(request, 'layout','login', self.context)

        # username = CustomUser.objects.get(email=email.lower()).username
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(request, user)
            if user.is_admin:
                return redirect('website:AdminList')
            else:
                return redirect('website:student-dashboard')
        else:
            messages.error(request, 'Username or Password is Incorrect')
            return renderhelper(request,'layout', 'login', self.context)

# Logout View  
class Logout(LoginRequiredMixin,View):
    context={}
    def get(self, request):
        request.session.flush()
        logout(request)
        return redirect('website:login')

# Student Registration   
class StudentRegistrationPageView(View):
    context = {}

    def get(self, request):
        if request.user.is_authenticated:
            messages.info(request, 'Sign out the current user and register a new user')
            return redirect('website:login')
        else:
            return renderhelper(request,'student', 'student_registration', self.context)

    def post(self, request):
        data = CustomUser()
            
        image = request.FILES.get('image')
        name = request.POST['name']
        email = request.POST['email']
        dob = request.POST['dob']
        phone = request.POST['phone']
        password = request.POST['password']
        username = request.POST['username']

        try:
            validate_password(password)
        except ValidationError as e:
            messages.error(request, ', '.join(e.messages))
            return renderhelper(request,'student', 'student_registration', self.context)
        
        try:
            data.name=name
            data.image=image
            if dob:
                dob_date = datetime.strptime(dob, '%Y-%m-%d').date()
                data.birth_date = dob_date
            data.phone=phone
            data.email=email
            data.username=username
            data.set_password(password)
            data.password_text=password
            data.is_student=True   
            data.save()
            login(request,data)
            messages.info(request, 'Account Created Successfully')
            return redirect('website:student-dashboard')
        except:
            messages.info(request, 'Something Went Wrong')
            return renderhelper(request,'student', 'student_registration', self.context)

# Student Dashboard
@method_decorator(student_required, name='dispatch')
class StudentDashboard(View):
    def get(self, request):
        context={}
        path="dashboard"
        user=request.user
        context['data']=user
        context['path']=path
        return renderhelper(request,'student','student_dashboard',context)
    

# Student Profile Edit  
@method_decorator(student_required, name='dispatch')
class StudentProfileEditView(View):
    def get(self, request):
        context={}
        data=request.user
        context['data']=data
        return renderhelper(request,'student', 'student_registration', context)

    def post(self, request):

        data = CustomUser.objects.get(id=request.user.id)

            
        image = request.FILES.get('image')
        print("image",image)
        name = request.POST['name']
        email = request.POST['email']
        dob = request.POST['dob']
        phone = request.POST['phone']
        password = request.POST['password']
        username = request.POST['username']

        try:
            validate_password(password)
        except ValidationError as e:
            messages.error(request, ', '.join(e.messages))
            return renderhelper(request,'student', 'student_registration', self.context)
        
        try:
            data.name=name
            if image:
                data.image=image
            if dob:
                dob_date = datetime.strptime(dob, '%Y-%m-%d').date()
                data.birth_date = dob_date
            data.phone=phone
            data.email=email
            data.username=username
            data.set_password(password)
            data.password_text=password
            data.is_student=True   
            data.save()
            login(request,data)
            messages.info(request, 'Successfully Updated')

        except:
            messages.info(request, 'Something Went Wrong')
        return redirect('website:student-dashboard')


# Admin Registration   
class AdminRegistrationPageView(View):
    context = {}

    def get(self, request):
        if request.user.is_authenticated:
            messages.info(request, 'Sign out the current user and register a new user')
            return redirect('website:login')
        else:
            return renderhelper(request,'admin', 'admin_registration', self.context)

    def post(self, request):
        data = CustomUser()
            
        image = request.FILES.get('image')
        name = request.POST['name']
        email = request.POST['email']
        dob = request.POST['dob']
        phone = request.POST['phone']
        password = request.POST['password']
        username = request.POST['username']

        try:
            validate_password(password)
        except ValidationError as e:
            messages.error(request, ', '.join(e.messages))
            return renderhelper(request,'admin', 'admin_registration', self.context)
        
        try:
            data.name=name
            if image:
                data.image=image
            if dob:
                dob_date = datetime.strptime(dob, '%Y-%m-%d').date()
                data.birth_date = dob_date
            data.phone=phone
            data.email=email
            data.username=username
            data.set_password(password)
            data.password_text=password
            data.is_admin=True   
            data.save()
            login(request,data)
            messages.info(request, 'Admin Created Successfully')
            return redirect('website:AdminList')
        except:
            messages.info(request, 'Something Went Wrong')
            return renderhelper(request,'admin', 'admin_registration', self.context)

# Admin Dashboard   
@method_decorator(admin_required, name='dispatch')    
class AdminDashboard(LoginRequiredMixin,View):
    def get(self, request):
        context = {}
        path="dashboard"
        conditions = Q()
        if is_ajax(request):
            page = request.GET.get('page', 1)
            context['page'] = page
            searchkey = request.GET.get('searchkey')
            status = request.GET.get('status')
            mark = request.GET.get('mark')

            type = request.GET.get('type')
            if type == '1':
                id = request.GET.get('id')
                vl = request.GET.get('vl')
                cat = CustomUser.objects.get(id=id)
                if vl == '2':
                    cat.is_active = False
                else:
                    cat.is_active = True
                cat.save()
                messages.info(request, 'Successfully Updated')

            if searchkey:
                conditions |= Q(name__icontains=searchkey)
            if status:
                conditions &= Q(is_active=status)
            if mark:
                id = request.GET.get('id')
                print(id)
                print("mark",mark)
                CustomUser.objects.filter(id=id).update(marks=mark)
                messages.info(request, 'Mark Updated Successfully')

            data_list = CustomUser.objects.filter(conditions,is_student=True).order_by('-id')
            paginator = Paginator(data_list, 15)

            try:
                datas = paginator.page(page)
            except PageNotAnInteger:
                datas = paginator.page(1)
            except EmptyPage:
                datas = paginator.page(paginator.num_pages)
            context['datas'] = datas
            template = loader.get_template('website/admin/admin_table.html')
            html_content = template.render(context, request)

            return JsonResponse({'status': True, 'template': html_content})


        data = CustomUser.objects.filter(is_student=True).order_by('-id')

        p = Paginator(data, 15)
        page_num = request.GET.get('page', 1)
        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        context["path"]=path
        context['datas'] = page
        context['page'] = page_num
        return renderhelper(request, 'admin', 'admin_view',context)

templates/website/student/student_dashboard.html
{% include "website/layout/header.html" %}

<section class="pt-5">
    <div class="container">
        <div class="text-end">
        <a class="btn btn-info btn-sm mb-1" style="width:fit-content" href="{% url 'website:student-profile'  %}">Edit Profile</a>
        </div>
        <div class="row">
          
            <div class="col-lg-4">
                {% if data.image %}
                <img src="{{data.image.url}}" alt="" class="w-100">
                {% endif %}
            
            </div>
            <div class="col-lg-8">
                <h4>Name: <span class="ms-3">{{data.name}}</span> </h4>
                <h4>Age: <span class="ms-3">{{data.age}} Years</span> </h4>
                <h4>DOB: <span class="ms-3">{{data.birth_date|date:"d/m/Y"}}</span> </h4>
                <h6 class="border-bottom mt-5">
                    Login Credantials
                </h6>
                <h4>Username: <span class="ms-3">{{data.username}}</span> </h4>
                <h4>Password: <span class="ms-3">{{data.password_text}}</span> </h4>



            </div>
        </div>

    
    </div>
</section>

{% include "website/layout/footer.html" %}

templates/website/student/student_registration.html
{% include "website/layout/header.html" %}

<section class="pt-5">
	<div class="container">
		<div class="text-center mt-5">
            {% if data %}
			<h3>Profile Edit </h3>
            {% else %}
            <h3>Student Registration </h3>
            {% endif %}
		</div>
    {% if messages %}
        <div id="message_div" class="succs-msg">
            {% for message in messages %}
                <label class="form-group" style="">
                    <p style="color:red;">{{message}}</p>
                </label>
            {% endfor %%}
        </div>
        {% endif %}
    <form method="post" class="" enctype="multipart/form-data" id="std_form">
      {% csrf_token %}
      <div class="row">
        <div class="col-lg-5">
            <div class="col-lg-12 col-sm-12 mb-4 mb-lg-0">
                <label class="form-label">UPLOAD IMAGE (Max size: 1 MB)</label>
                <input type="file" class="dropify" data-bs-height="180" accept=".jpg,.jpeg,.png,.gif,.mp4,.avi,.mkv,.mov" name="image"  id="image" {% if data.image %} data-default-file="{{data.image.url}}" {% else %} required{% endif %} {% if not data.image %} required {% endif %}/>
                <span id="imageSizeInfo" class="text-muted">Max size: 1 MB</span>
            </div>

        </div>
        <div class="col-lg-7 row">
           <div class="form-group col-lg-12">
              <label for="exampleInputEmail1" class="form-label">Name</label>
              <input type="text" class="form-control" id="exampleInputEmail1"
                  placeholder="Title"  name="name"  required {% if data.name %} value="{{data.name}}" {% endif %} maxlength="30" minlength="2">
           </div>
           <div class="form-group col-lg-12 mt-3">
            <label for="exampleInputEmail1" class="form-label">Email</label>
            <input type="email" class="form-control" id="exampleInputEmail1"
                placeholder="Email"  name="email"  required {% if data.email %} value="{{data.email}}" {% endif %} >
         </div>
           <div class="form-group col-lg-12 mt-3">
            <label for="exampleInputEmail1" class="form-label">Date Of Birth (1990-01-01 - 2020-01-01)</label>
            <input type="date" class="form-control" id="exampleInputEmail1"
                placeholder="DOB"  name="dob"  required {% if data.birth_date %} value="{{data.birth_date|date:'Y-m-d'}}" {% endif %} min="1990-01-01" max="2020-01-01">
            </div>
            <div class="form-group col-lg-12 mt-3">
              <label for="exampleInputEmail1" class="form-label">Phone</label>
              <input type="text" class="form-control" id="exampleInputEmail1"
                  placeholder="phone"  name="phone"  required {% if data.phone %} value="{{data.phone}}" {% endif %}  maxlength="10" onkeypress='return restrictAlphabets(event)'>
            </div>

            <h6 class="mt-4">Login Credentials</h6>
            <div class="form-group col-lg-12 mt-3">
              <label for="exampleInputEmail1" class="form-label">Username</label>
              <input type="text" class="form-control" id="exampleInputEmail1"
                  placeholder="username"  name="username"  required {% if data.username %} value="{{data.username}}" {% endif %} maxlength="15" minlength="5">
            </div>
            <div class="form-group col-lg-12 mt-3">
              <label for="exampleInputEmail1" class="form-label">Password</label>
              <input type="text" class="form-control" id="password"
                  placeholder="password"  name="password"  required {% if data.password_text %} value="{{data.password_text}}" {% endif %}>
            </div>
            <button class="btn btn-success btn-pill mt-4" type="submit" id="std_btn">{% if data %} Update {% else %}Create       {% endif %}</button>
            {% if data %}
            <button class="btn btn-danger btn-pill mt-4 " style="width:fit-content"><a class=" text-white text-decoration-none" href="{% url 'website:student-dashboard'  %}">Cancel</a> </button>
            {% else %}
            <p class="pt-5 fs-6">Already have an account? <span><a href="{% url 'website:login' %}">Login</a></span> </p>
            {% endif %}
       </div>

    </div>
    </form>
	</div>
</section>

{% include "website/layout/footer.html" %}